# HMSC analysis

```{r load_data07}

rm(list=ls()) #clear environment
load("data/squirrels_data.Rdata")
options(contrasts = c('contr.sum','contr.poly'))
```

```{r hmsc_model_list}

# Select modelchain of interest
load("hmsc/fit_model.3a_250_10.Rdata")

levels.1a <- c("species","index500","season","logseqdepth","Random: animal")
levels.1b <- c("species","index500","season","logseqdepth","Random: animal", "Random: sampling_site")
levels.2a <- c("species","index500","season","species:index500","logseqdepth","Random: animal")
levels.2b <- c("species","index500","season","species:index500","logseqdepth","Random: animal", "Random: sampling_site")
levels.3a <- c("species","index500","season","species:season","logseqdepth","Random: animal")
levels.3b <- c("species","index500","season","species:season","logseqdepth","Random: animal", "Random: sampling_site")
levels.4a <- c("species","index500","season","species:index500","species:season","logseqdepth","Random: animal")
levels.4b <- c("species","index500","season","logseqdepth","species:index500","species:season","Random: animal", "Random: sampling_site")
```

## Variance partitioning

```{r hmsc_varpart, warning=FALSE, comments="", message=FALSE}
# Compute variance partitioning
varpart=computeVariancePartitioning(m)

varpart$vals %>%
   as.data.frame() %>%
   rownames_to_column(var="variable") %>%
   pivot_longer(!variable, names_to = "genome", values_to = "value") %>%
   mutate(variable=factor(variable, levels=levels.3a)) %>%
   group_by(variable) %>%
   summarise(mean=mean(value)*100,sd=sd(value)*100) %>%
   tt()
```

```{r hmsc_varpart_plot, warning=FALSE, comments="", message=FALSE, fig.dim=c(8, 10)}
# Basal tree
varpart_tree <- genome_tree %>%
        keep.tip(., tip=m$spNames) 

# Varpart table
varpart_table <- varpart$vals %>%
   as.data.frame() %>%
   rownames_to_column(var="variable") %>%
   pivot_longer(!variable, names_to = "genome", values_to = "value") %>%
   mutate(variable=factor(variable, levels=rev(levels.3a))) %>%
   mutate(genome=factor(genome, levels=rev(varpart_tree$tip.label)))

# Phylums
phylums <- genome_metadata %>%
    filter(genome %in% varpart_tree$tip.label) %>%
    arrange(match(genome, varpart_tree$tip.label)) %>%
    mutate(phylum = factor(phylum, levels = unique(phylum))) %>%
    column_to_rownames(var = "genome") %>%
    select(phylum)

# Basal ggtree
varpart_tree <- varpart_tree %>%
        force.ultrametric(.,method="extend") %>%
        ggtree(., size = 0.3)

# Add phylum colors next to the tree tips
varpart_tree <- gheatmap(varpart_tree, phylums, offset=-0.2, width=0.1, colnames=FALSE) +
   scale_fill_manual(values=custom_colors)+
      labs(fill="Phylum")

#Reset fill scale to use a different colour profile in the heatmap
varpart_tree <- varpart_tree + new_scale_fill()

# Add variance stacked barplot
vertical_tree <-  varpart_tree +
        scale_fill_manual(values=c("#83bb90","#cccccc","#ed8a45","#b2b530","#be3e2b","#12738f","#f6de9c")) + #"#122f3d"
        geom_fruit(
             data=varpart_table,
             geom=geom_bar,
             mapping = aes(x=value, y=genome, fill=variable, group=variable),
             pwidth = 2,
             offset = 0.05,
             width= 1,
             orientation="y",
             stat="identity")+
      labs(fill="Variable")

vertical_tree
```
## Posterior estimates

```{r hmsc_postestimates, warning=FALSE, comments="", message=FALSE, fig.dim=c(10, 10)}
# Select desired support threshold
support=0.9
negsupport=1-support

# Basal tree
postestimates_tree <- genome_tree %>%
        keep.tip(., tip=m$spNames) 

#plotBeta(hM=m, post=getPostEstimate(hM=m, parName="Beta"), param = "Support", plotTree = TRUE, covNamesNumbers=c(1,0))

# Posterior estimate table
post_beta <- getPostEstimate(hM=m, parName="Beta")$support %>%
    as.data.frame() %>%
    mutate(variable=m$covNames) %>%
    pivot_longer(!variable, names_to = "genome", values_to = "value") %>%
    mutate(genome=factor(genome, levels=rev(postestimates_tree$tip.label))) %>%
    mutate(value = case_when(
          value >= support ~ "Positive",
          value <= negsupport ~ "Negative",
          TRUE ~ "Neutral")) %>%
    mutate(value=factor(value, levels=c("Positive","Neutral","Negative"))) %>%
    pivot_wider(names_from = variable, values_from = value) %>%
    rename(intercept=2,
            Sc=3,
            index500=4,
            autumn=5,
            winter=6,
            logseqdepth=7,
            "Sc:autumn"=8,
            "Sc:winter"=9) %>%
   column_to_rownames(var="genome") %>%
  select(-intercept) 
  
#Phylums
phylums <- genome_metadata %>%
    filter(genome %in% postestimates_tree$tip.label) %>%
    arrange(match(genome, varpart_tree$tip.label)) %>%
    mutate(phylum = factor(phylum, levels = unique(phylum))) %>%
    column_to_rownames(var = "genome") %>%
    select(phylum)


# Basal ggtree
postestimates_tree <- postestimates_tree %>%
        force.ultrametric(.,method="extend") %>%
        ggtree(., size = 0.3)
        

#Add phylum colors next to the tree tips
postestimates_tree <- gheatmap(postestimates_tree, phylums, offset=-0.2, width=0.1, colnames=FALSE) +
      scale_fill_manual(values=custom_colors)+
      labs(fill="Phylum")

#Reset fill scale to use a different colour profile in the heatmap
postestimates_tree <- postestimates_tree + new_scale_fill()

# Add posterior significant heatmap

postestimates_tree <- gheatmap(postestimates_tree, post_beta, offset=0, width=0.5, colnames=TRUE, colnames_position="top",colnames_angle=90, colnames_offset_y=1, hjust=0) +
        scale_fill_manual(values=c("#be3e2b","#f4f4f4","#b2b530"))+
        labs(fill="Trend") 

postestimates_tree +
        vexpand(.30, 1)  # expand top 

```
## Correlations among bacteria

```{r hmsc_correlations, warning=FALSE, comments="", message=FALSE, fig.dim=c(8,8)}
#Compute the residual correlation matrix
OmegaCor = computeAssociations(m)

# Reference tree (for sorting genomes)
genome_tree_subset <- genome_tree %>%
        keep.tip(., tip=m$spNames) 


#Co-occurrence matrix at the animal level
supportLevel = 0.95
toPlot = ((OmegaCor[[1]]$support>supportLevel)
          + (OmegaCor[[1]]$support<(1-supportLevel))>0)*OmegaCor[[1]]$mean

matrix <- toPlot %>% 
      as.data.frame() %>%
      rownames_to_column(var="genome1") %>%
      pivot_longer(!genome1, names_to = "genome2", values_to = "cor") %>%
      mutate(genome1= factor(genome1, levels=genome_tree_subset$tip.label)) %>%
      mutate(genome2= factor(genome2, levels=genome_tree_subset$tip.label)) %>%
      ggplot(aes(x = genome1, y = genome2, fill = cor)) +
            geom_tile() + 
            scale_fill_gradient2(low = "#be3e2b",
                       mid = "#f4f4f4",
                       high = "#b2b530")+
            theme_void() +
            theme(legend.position = "none") 

corr.legend <- get_legend(matrix, position="right") 
corr.legend <- as_ggplot(corr.legend)

vtree <- genome_tree_subset %>%
  force.ultrametric(.,method="extend") %>%
  ggtree(., expand=1.5) +
  hexpand(0.5)

#Add phylum colors next to the tree tips
vtree <- gheatmap(vtree, phylums, offset=-0.2, width=0.6, colnames=FALSE) +
      scale_fill_manual(values=custom_colors) +
      theme(legend.position = 'none')

vtreeD <- genome_tree_subset %>%
  force.ultrametric(.,method="extend") %>%
  ggtree(., expand=1.5, layout="dendrogram") 

#Add phylum colors next to the tree tips
vtreeD <- gheatmap(vtreeD, phylums, offset=-0.2, width=0.8, colnames=FALSE) +
      scale_fill_manual(values=custom_colors) +
      theme(legend.position = 'none')


#create composite figure
grid.arrange(grobs = list(vtreeD,matrix,vtree,corr.legend),
             layout_matrix = rbind(c(5,5,1,1,1,1,1,1,1,1,1,5),
                                   c(5,5,1,1,1,1,1,1,1,1,1,5),
                                   c(5,5,1,1,1,1,1,1,1,1,1,5),
                                   c(3,3,2,2,2,2,2,2,2,2,2,5),
                                   c(3,3,2,2,2,2,2,2,2,2,2,5),
                                   c(3,3,2,2,2,2,2,2,2,2,2,5),
                                   c(3,3,2,2,2,2,2,2,2,2,2,4),
                                   c(3,3,2,2,2,2,2,2,2,2,2,4),
                                   c(3,3,2,2,2,2,2,2,2,2,2,4),
                                   c(3,3,2,2,2,2,2,2,2,2,2,4),
                                   c(3,3,2,2,2,2,2,2,2,2,2,5),
                                   c(3,3,2,2,2,2,2,2,2,2,2,5),
                                   c(3,3,2,2,2,2,2,2,2,2,2,5),
                                   c(3,3,2,2,2,2,2,2,2,2,2,5)))

```
## Predicted MAG abundance by species

```{r hmsc_pred_species, warning=FALSE, comments="", message=FALSE, fig.dim=c(8, 10)}
# Overall species prediction
pred_species <- constructGradient(m, 
                      focalVariable = "species", 
                      non.focalVariables = 1, 
                      ngrid=gradientlength) %>%
             predict(m, Gradient = ., expected = TRUE) %>%
             as.data.frame() %>%
             mutate(species=c("Sciurus vulgaris","Sciurus carolinensis")) %>%
             pivot_longer(!species, names_to = "genome", values_to = "value") %>%
             mutate(genome = sub("(.*\\..*\\.)[^.]+.*", "\\1", genome)) %>% #remove iteration suffix
             mutate(genome =  sub("\\.$", "", genome))

pred_species %>%
      pivot_wider(names_from = species, values_from = value) %>%
      unnest(c(`Sciurus carolinensis`, `Sciurus vulgaris`)) %>%
      mutate(diff.red_grey = `Sciurus carolinensis` - `Sciurus vulgaris`) %>%
      select(genome, diff.red_grey) %>%
      left_join(genome_metadata, by=join_by(genome==genome)) %>%
      mutate(genome= factor(genome, levels=genome_tree_subset$tip.label)) %>%
      ggplot(., aes(y=genome, x=diff.red_grey, fill=phylum, color=phylum)) +
          scale_color_manual(values=custom_colors)+
          geom_vline(xintercept = 0)+
          scale_fill_manual(values=alpha(custom_colors,0.3))+
          geom_boxplot(outlier.shape = NA) +
          theme_classic() +
          theme(axis.text.y = element_blank())
```

## Predicted MAG abundance by urbanization

```{r hmsc_pred_urb}
gradient = seq(0,1, by=0.1)
gradientlength = length(gradient)

pred_urban <- constructGradient(m,
                      focalVariable = "index500",
                      non.focalVariables = list(logseqdepth=list(1),species=list(1), season=list(1)),
                      ngrid=gradientlength) %>%
                      predict(m, Gradient = ., expected = TRUE) %>%
                      do.call(rbind,.) %>%
                      as.data.frame() %>%
                      mutate(index500=rep(gradient,1000)) %>%
                      pivot_longer(-c(index500), names_to = "genome", values_to = "value")

support=0.9
negsupport=1-support

getPostEstimate(hM=m, parName="Beta")$support %>%
    as.data.frame() %>%
    mutate(variable=m$covNames) %>%
    pivot_longer(!variable, names_to = "genome", values_to = "value") %>%
    mutate(trend = case_when(
          value >= support ~ "Positive",
          value <= negsupport ~ "Negative",
          TRUE ~ "Neutral")) %>%
    filter(variable=="index500") %>%
    select(genome,trend) %>%
    left_join(pred_urban, by=join_by(genome==genome)) %>%
    group_by(genome, trend, index500) %>%
    summarize(value = mean(value, na.rm = TRUE)) %>%
    left_join(genome_metadata, by=join_by(genome == genome)) %>%
    ggplot(aes(x=index500, y=value, group=genome, color=phylum, linetype=trend)) +
        geom_line() +
        scale_linetype_manual(values=c("solid","dashed","solid")) +
        scale_color_manual(values=custom_colors) +
        facet_grid(fct_rev(trend) ~ phylum) +
        labs(y="Genome abundance (log)",x="Urbanization index") +
        theme(legend.position = "none") +
        theme_minimal() +
         theme(legend.position = "none",
               axis.text.x = element_text(angle = 45, hjust = 0.8,),
               axis.line.x = element_line(size = 0.5, linetype = "solid", colour = "black"),
               strip.text.x = element_text(angle = 90, hjust = 0,)
)
```


```{r hmsc_pred_season, warning=FALSE, comments="", message=FALSE, fig.dim=c(8, 10)}
# # Overall season prediction
# pred_season <- constructGradient(m, 
#                       focalVariable = "season", 
#                       non.focalVariables = 1, 
#                       ngrid=gradientlength) %>%
#              predict(m, Gradient = ., expected = TRUE) %>%
#              as.data.frame() %>%
#              mutate(season=c("autumn","spring-summer","winter")) %>%
#              pivot_longer(!season, names_to = "genome", values_to = "value") 
# 
# pred_season %>% 
#       mutate(genome= factor(genome, levels=genome_tree_subset$tip.label)) %>%
#       group_by(genome, season) %>%
#       summarize(value = mean(value, na.rm = TRUE)) %>%
#       left_join(genome_metadata, by=join_by(genome==genome)) %>%
#       ggplot(., aes(y=value, x=season, group=genome, color=phylum, fill=phylum)) +
#       facet_grid(phylum~ season) +
#       scale_color_manual(values=custom_colors)+
#       scale_fill_manual(values=alpha(custom_colors,0.3))+
#       geom_boxplot(outlier.shape = NA) +
#       theme_classic() +
#       theme(axis.text.y = element_blank())
    
```

## Functional predictions

```{r GIFTs_data_preparation2, echo = T, results = 'hide', warning=FALSE, message=FALSE, eval=FALSE}

tss <- function(abund){sweep(abund, 2, colSums(abund), FUN="/")} 

genome_counts <- genome_counts %>%
  column_to_rownames(var="genome")
genome_kegg <- genome_kegg %>%
  column_to_rownames(var="genome")
genome_gifts <- genome_gifts %>%
  column_to_rownames(var="genome")

#Get list of present MAGs
present_MAGs <- genome_counts %>%
  filter(rownames(.) %in% varpart_tree$tip.label) %>%
  rownames()

#Align distillr annotations with present MAGs and remove all-zero and all-one traits
present_MAGs <- present_MAGs[present_MAGs %in% rownames(genome_gifts)]

GIFTs_elements <- genome_gifts[present_MAGs,] %>%
  select_if(~!all(. == 0)) %>%  #remove all-zero modules
  select_if(~!all(. == 1)) #remove all-one modules

#Aggregate element-level GIFTs into the function level
GIFTs_functions <- to.functions(GIFTs_elements,GIFT_db)

#Aggregate function-level GIFTs into overall Biosynthesis, Degradation and Structural GIFTs and get overall metabolic capacity indices per MAG (at the domain level)
GIFTs_domains <- to.domains(GIFTs_functions,GIFT_db) %>% as.data.frame() %>%
  mutate(Overall=rowMeans(select(.,Biosynthesis,Structure,Degradation), na.rm=TRUE))


# GIFTs_elements_community <- genome_counts %>%
#   tss() %>%
#   to.community(GIFTs_elements,.,GIFT_db)
# 
# GIFTs_functions_community <- genome_counts %>%
#   tss() %>%
#   to.community(GIFTs_functions,.,GIFT_db)
# 
# GIFTs_domains_community <- genome_counts %>%
#   tss() %>%
#   to.community(GIFTs_domains,.,GIFT_db)

```

```{r community_prova, eval=FALSE}
community_elements <- pred_urban %>%
  group_by(index500, genome) %>%
  mutate(row_id = row_number()) %>%
  pivot_wider(names_from = genome, values_from = value) %>%
  ungroup() %>%
  group_split(row_id) %>%
  as.list() %>%
  lapply(., FUN = function(x){x %>%
    select(-row_id) %>%
    column_to_rownames(var = "index500") %>%
    as.data.frame() %>%
    exp() %>%
    t() %>%
    tss() %>%
    to.community(GIFTs_elements,.,GIFT_db) %>%
    as.data.frame() %>%
    rownames_to_column(var="index500")
   })



calculate_slope <- function(x) {
  lm_fit <- lm(unlist(x) ~ seq_along(unlist(x)))
  coef(lm_fit)[2]
}

element_predictions <- map_dfc(community_elements, function(mat) {
      mat %>%
        column_to_rownames(var = "index500") %>%
        t() %>%
        as.data.frame() %>%
        rowwise() %>%
        mutate(slope = calculate_slope(c_across(everything()))) %>%
        select(slope) }) %>%
      t() %>%
      as.data.frame() %>%
      set_names(colnames(community_elements[[1]])[-1]) %>%
      rownames_to_column(var="iteration") %>%
      pivot_longer(!iteration, names_to="trait",values_to="value") %>%
      group_by(trait) %>%
      summarise(mean=mean(value),
        p1 = quantile(value, probs = 0.1),
        p9 = quantile(value, probs = 0.9),
        positive_support = sum(value > 0)/1000,
        negative_support = sum(value < 0)/1000) %>%
      arrange(-positive_support)
```


