---
title: "HMSC analysis"
author: "Claudia Romeo & Antton Alberdi"
date: "2024sc-01-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load libraries

```{r libraries, warning=FALSE, comments="", message=FALSE}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(phyloseq))
suppressPackageStartupMessages(library(ape))
suppressPackageStartupMessages(library(Hmsc))
suppressPackageStartupMessages(library(distillR))
suppressPackageStartupMessages(library(phytools))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(ggtree))
suppressPackageStartupMessages(library(ggnewscale))
suppressPackageStartupMessages(library(ggtreeExtra))
suppressPackageStartupMessages(library(gridExtra))
suppressPackageStartupMessages(library(hilldiv2))
suppressPackageStartupMessages(library(tinytable))
suppressPackageStartupMessages(library(corrplot))
```

## Load data

```{r load_data}

rm(list=ls()) #clear environment
load("data/squirrels_data.Rdata")
```

## Model list

```{r hmsc_model_list}

# Select modelchain of interest
load("hmsc/fit_model.4b_250_10.Rdata")

levels.1a <- c("species","index500","season","logseqdepth","Random: animal")
levels.1b <- c("species","index500","season","logseqdepth","Random: animal", "Random: sampling_site")
levels.2a <- c("species","index500","season","species:index500","logseqdepth","Random: animal")
levels.2b <- c("species","index500","season","species:index500","logseqdepth","Random: animal", "Random: sampling_site")
levels.3a <- c("species","index500","season","species:season","logseqdepth","Random: animal")
levels.3b <- c("species","index500","season","species:season","logseqdepth","Random: animal", "Random: sampling_site")
levels.4a <- c("species","index500","season","species:index500","species:season","logseqdepth","Random: animal")
levels.4b <- c("species","index500","season","logseqdepth","species:index500","species:season","Random: animal", "Random: sampling_site")


```


## Compute variance partitioning

```{r hmsc_varpart, warning=FALSE, comments="", message=FALSE}


# Compute variance partitioning
varpart=computeVariancePartitioning(m)

varpart$vals %>%
   as.data.frame() %>%
   rownames_to_column(var="variable") %>%
   pivot_longer(!variable, names_to = "genome", values_to = "value") %>%
   mutate(variable=factor(variable, levels=levels.3b)) %>%
   group_by(variable) %>%
   summarise(mean=mean(value)*100,sd=sd(value)*100) %>%
   tt()
```

```{r hmsc_varpart_plot, warning=FALSE, comments="", message=FALSE}
# Basal tree
varpart_tree <- genome_tree %>%
        keep.tip(., tip=m$spNames) 

#Varpart table
varpart_table <- varpart$vals %>%
   as.data.frame() %>%
   rownames_to_column(var="variable") %>%
   pivot_longer(!variable, names_to = "genome", values_to = "value") %>%
   mutate(variable=factor(variable, levels=rev(levels.4b))) %>%
   mutate(genome=factor(genome, levels=rev(varpart_tree$tip.label)))

#Phylums
phylum_colors <- read_tsv("https://raw.githubusercontent.com/earthhologenome/EHI_taxonomy_colour/main/ehi_phylum_colors.tsv") %>%
  right_join(genome_metadata, by=join_by(phylum == phylum)) %>%
    filter(genome %in% varpart_tree$tip.label) %>%
    arrange(match(genome, varpart_tree$tip.label)) %>%
    mutate(phylum = factor(phylum, levels = unique(phylum))) %>%
    column_to_rownames(var = "genome") %>%
    select(phylum)


colors_alphabetic <- read_tsv("https://raw.githubusercontent.com/earthhologenome/EHI_taxonomy_colour/main/ehi_phylum_colors.tsv") %>%
  right_join(genome_metadata, by=join_by(phylum == phylum)) %>%
    filter(genome %in% varpart_tree$tip.label) %>%
    arrange(match(genome, varpart_tree$tip.label)) %>%
     select(phylum, colors) %>%
    unique() %>%
    arrange(phylum) %>%
    select(colors) %>%
    pull()

# Basal ggtree
varpart_tree <- varpart_tree %>%
        force.ultrametric(.,method="extend") %>%
        ggtree(., size = 0.3)

# Add phylum colors next to the tree tips
varpart_tree <- gheatmap(varpart_tree, phylum_colors, offset=-0.2, width=0.1, colnames=FALSE) +
   scale_fill_manual(values=colors_alphabetic)+
      labs(fill="Phylum")

#Reset fill scale to use a different colour profile in the heatmap
varpart_tree <- varpart_tree + new_scale_fill()

# Add variance stacked barplot
vertical_tree <-  varpart_tree +
        #scale_fill_manual(values=c("#34738f","#cccccc","#ed8a45","#b2b530","#be3e2b","#f6de6c","#83bb90"))+
        scale_fill_manual(values=c("#122f3d","#34738f","#cccccc","#ed8a45","#b2b530","#be3e2b","#83bb90","#f6de6c"))+
        geom_fruit(
             data=varpart_table,
             geom=geom_bar,
             mapping = aes(x=value, y=genome, fill=variable, group=variable),
             pwidth = 2,
             offset = 0.05,
             width= 1,
             orientation="y",
             stat="identity")+
      labs(fill="Variable")

vertical_tree
```

```{r hmsc_postestimates, warning=FALSE, comments="", message=FALSE}
# Select desired support threshold
support=0.9
negsupport=1-support

# Basal tree
postestimates_tree <- genome_tree %>%
        keep.tip(., tip=m$spNames) 

#plotBeta(hM=m, post=getPostEstimate(hM=m, parName="Beta"), param = "Support", plotTree = TRUE, covNamesNumbers=c(1,0))

# Posterior estimate table
post_beta <- getPostEstimate(hM=m, parName="Beta")$support %>%
    as.data.frame() %>%
    mutate(variable=m$covNames) %>%
    pivot_longer(!variable, names_to = "genome", values_to = "value") %>%
    mutate(genome=factor(genome, levels=rev(postestimates_tree$tip.label))) %>%
    mutate(value = case_when(
          value >= support ~ "Positive",
          value <= negsupport ~ "Negative",
          TRUE ~ "Neutral")) %>%
    mutate(value=factor(value, levels=c("Positive","Neutral","Negative"))) %>%
    pivot_wider(names_from = variable, values_from = value) %>%
    # rename(intercept=2,
    #          species.grey=3,
    #          index500=4,
    #          season.autumn=5,
    #          season.winter=6,
    #          logseqdepth=7,
    #          species.grey_season.autumn=8,
    #          species.grey_season.winter=9) %>%
   # select(genome,builtup,species,season_autumn,season_winter, builtup_species,species_season_autumn,species_season_winter) %>%
    #rename(intercept=2, sp_vulgaris=3, area_semi=4, area_urban=5, season_spring=6, season_winter=7, logseqdepth=8, sp_vulgarisxarea_semi=9, sp_vulgarisxarea_urban =10, sp_vulgarisxseason_spring=11, sp_vulgarisxseason_winter=12) %>%
    #select(genome,sp_vulgaris,area_semi,area_urban,sp_vulgarisxarea_semi,sp_vulgarisxarea_urban,season_spring,season_winter,sp_vulgarisxseason_spring,sp_vulgarisxseason_winter) %>%
    column_to_rownames(var="genome")

#Phylums
phylum_colors <- read_tsv("https://raw.githubusercontent.com/earthhologenome/EHI_taxonomy_colour/main/ehi_phylum_colors.tsv") %>%
  right_join(genome_metadata, by=join_by(phylum == phylum)) %>%
    filter(genome %in% postestimates_tree$tip.label) %>%
    arrange(match(genome, varpart_tree$tip.label)) %>%
    mutate(phylum = factor(phylum, levels = unique(phylum))) %>%
    column_to_rownames(var = "genome") %>%
    select(phylum)


colors_alphabetic <- read_tsv("https://raw.githubusercontent.com/earthhologenome/EHI_taxonomy_colour/main/ehi_phylum_colors.tsv") %>%
  right_join(genome_metadata, by=join_by(phylum == phylum)) %>%
    filter(genome %in% postestimates_tree$tip.label) %>%
    arrange(match(genome, varpart_tree$tip.label)) %>%
     select(phylum, colors) %>%
    unique() %>%
    arrange(phylum) %>%
    select(colors) %>%
    pull()

# Basal ggtree
postestimates_tree <- postestimates_tree %>%
        force.ultrametric(.,method="extend") %>%
        ggtree(., size = 0.3)

#Add phylum colors next to the tree tips
postestimates_tree <- gheatmap(postestimates_tree, phylum_colors, offset=-0.2, width=0.1, colnames=FALSE) +
      scale_fill_manual(values=colors_alphabetic)+
      labs(fill="Phylum")

#Reset fill scale to use a different colour profile in the heatmap
postestimates_tree <- postestimates_tree + new_scale_fill()

# Add posterior significant heatmap

postestimates_tree <- gheatmap(postestimates_tree, post_beta, offset=0, width=0.5, colnames=TRUE, colnames_position="top",colnames_angle=90, colnames_offset_y=1, hjust=0) +
        scale_fill_manual(values=c("#be3e2b","#f4f4f4","#b2b530"))+
        labs(fill="Trend")

postestimates_tree +
        vexpand(.25, 1) # expand top 
```


```{r hmsc_correlations, warning=FALSE, comments="", message=FALSE}
#Compute the residual correlation matrix
OmegaCor = computeAssociations(m)

# Refernece tree (for sorting genomes)
genome_tree_subset <- genome_tree %>%
        keep.tip(., tip=m$spNames) 


#Co-occurrence matrix at the animal level
supportLevel = 0.95
toPlot = ((OmegaCor[[1]]$support>supportLevel)
          + (OmegaCor[[1]]$support<(1-supportLevel))>0)*OmegaCor[[1]]$mean

matrix <- toPlot %>% 
      as.data.frame() %>%
      rownames_to_column(var="genome1") %>%
      pivot_longer(!genome1, names_to = "genome2", values_to = "cor") %>%
      mutate(genome1= factor(genome1, levels=genome_tree_subset$tip.label)) %>%
      mutate(genome2= factor(genome2, levels=genome_tree_subset$tip.label)) %>%
      ggplot(aes(x = genome1, y = genome2, fill = cor)) +
            geom_tile() + 
            scale_fill_gradient2(low = "#be3e2b",
                       mid = "#f4f4f4",
                       high = "#b2b530")+
            theme_void()

vtree <- genome_tree_subset %>%
  force.ultrametric(.,method="extend") %>%
  ggtree(.)
  
#create composite figure
grid.arrange(grobs = list(vtree,matrix,vtree),
             layout_matrix = rbind(c(4,1,1,1,1,1,1,1,1,1,1,1),
                                   c(3,2,2,2,2,2,2,2,2,2,2,2),
                                   c(3,2,2,2,2,2,2,2,2,2,2,2),
                                   c(3,2,2,2,2,2,2,2,2,2,2,2),
                                   c(3,2,2,2,2,2,2,2,2,2,2,2),
                                   c(3,2,2,2,2,2,2,2,2,2,2,2),
                                   c(3,2,2,2,2,2,2,2,2,2,2,2),
                                   c(3,2,2,2,2,2,2,2,2,2,2,2),
                                   c(3,2,2,2,2,2,2,2,2,2,2,2),
                                   c(3,2,2,2,2,2,2,2,2,2,2,2),
                                   c(3,2,2,2,2,2,2,2,2,2,2,2),
                                   c(3,2,2,2,2,2,2,2,2,2,2,2)))
```

```{r hmsc_pred_species, warning=FALSE, comments="", message=FALSE}
# Overall species prediction
pred_species <- constructGradient(m, 
                      focalVariable = "species", 
                      non.focalVariables = 1, 
                      ngrid=gradientlength) %>%
             predict(m, Gradient = ., expected = TRUE) %>%
             as.data.frame() %>%
             mutate(species=c("Sciurus vulgaris","Sciurus carolinensis")) %>%
             pivot_longer(!species, names_to = "genome", values_to = "value") %>%
             mutate(genome = sub("(.*\\..*\\.)[^.]+.*", "\\1", genome)) %>% #remove iteration suffix
             mutate(genome =  sub("\\.$", "", genome))
```

```{r hmsc_pred_species_plot, warning=FALSE, comments="", message=FALSE}
pred_species %>%
      pivot_wider(names_from = species, values_from = value) %>%
      unnest(c(`Sciurus carolinensis`, `Sciurus vulgaris`)) %>%
      mutate(diff_grey.red = `Sciurus carolinensis` - `Sciurus vulgaris`) %>%
      select(genome, diff_grey.red) %>%
      left_join(genome_metadata, by=join_by(genome==genome)) %>%
      mutate(genome= factor(genome, levels=genome_tree_subset$tip.label)) %>%
      ggplot(., aes(y=genome, x=diff_grey.red, fill=phylum, color=phylum)) +
          scale_color_manual(values=colors_alphabetic)+
          geom_vline(xintercept = 0)+
          scale_fill_manual(values=paste0(colors_alphabetic,"80"))+
          geom_boxplot(outlier.shape = NA) +
          theme_classic() +
          theme(axis.text.y = element_blank())
```

```{r hmsc_pred_area, warning=FALSE, comments="", message=FALSE}
gradient = c(0:100)
gradientlength = length(gradient)

# Overall urbanisation prediction
pred_urban <- constructGradient(m, 
                      focalVariable = "index500", 
                      non.focalVariables = 1, 
                      ngrid=gradientlength) %>%
             predict(m, Gradient = ., expected = TRUE) %>%
            do.call(rbind,.) %>%
            as.data.frame() %>%
            mutate(index500=rep(gradient,1000)) %>%
            pivot_longer(-index500, names_to = "genome", values_to = "value") %>%
             mutate(genome = sub("(.*\\..*\\.)[^.]+.*", "\\1", genome)) %>% #remove iteration suffix
             mutate(genome =  sub("\\.$", "", genome)) #remove iteration suffix
```

```{r hmsc_pred_area_plot, warning=FALSE, comments="", message=FALSE}
pred_urban %>%
      mutate(genome=factor(genome, levels=genome_tree_subset$tip.label)) %>%
      group_by(index500,genome) %>%
      summarise(mean=mean(value)) %>%
      ggplot(., aes(y=genome, x=index500, fill=mean, color=mean)) +
          geom_tile() +
          scale_fill_gradient(low = "#f4f4f4", high = "steelblue", na.value="white") +
          theme_classic()+ 
          theme(
            axis.title.y=element_blank(),
            axis.text.y=element_blank(),
            axis.ticks.y=element_blank()
          )
```

```{r hmsc_pred_area, warning=FALSE, comments="", message=FALSE}

# Urbanisation Sciurus vulgaris prediction
pred_urban_SciVu <- constructGradient(m, 
                      focalVariable = "index500", 
                      non.focalVariables = list(species=list(3,"Sciurus vulgaris")), 
                      ngrid=gradientlength) %>%
             predict(m, Gradient = ., expected = TRUE)

# Urbanisation Sciurus carolinensis prediction
pred_urban_SciCa <- constructGradient(m, 
                      focalVariable = "index500", 
                      non.focalVariables = list(species=list(3,"Sciurus carolinensis")), 
                      ngrid=gradientlength) %>%
             predict(m, Gradient = ., expected = TRUE)
```

```{r hmsc_pred_area_plot, warning=FALSE, comments="", message=FALSE}
pred_urban_SciVu %>%
      mutate(genome=factor(genome, levels=genome_tree_subset$tip.label)) %>%
      group_by(index500,genome) %>%
      summarise(mean=mean(value)) %>%
      ggplot(., aes(y=genome, x=index500, fill=mean, color=mean)) +
          geom_tile() +
          scale_fill_gradient(low = "#f4f4f4", high = "steelblue", na.value="white") +
          theme_classic()+ 
          theme(
            axis.title.y=element_blank(),
            axis.text.y=element_blank(),
            axis.ticks.y=element_blank()
          )
```
